### ISSUE TITLE
Open Source Friday - Upptime - 03-01-2024

### ISSUE THREAD

**Issue by AnandChowdhary** [githubevents/open-source-friday#26]
### Name

Anand Chowdhary

### GitHub Handle

AnandChowdhary

### Project Name

Upptime

### Project Repo

https://github.com/upptime/upptime

### Stream Date

- [X] Yes
- [ ] Not yet

### Dates

03-01-2024

### Twitter URL

https://twitter.com/AnandChowdhary

### LinkedIn URL

https://www.linkedin.com/in/AnandChowdhary

### Additional Information

Reference: Message from @ladykerr in the #github-stars channel in the github-partners Slack.

**Comment by LadyKerr** [comment]
duplicate: https://github.com/githubevents/open-source-friday/issues/64
