### ISSUE TITLE
Open Source Friday - Nuxt.js - 03-08-2024

### ISSUE THREAD

**Issue by manniL** [githubevents/open-source-friday#32]
### Name

Alexander Lichter

### GitHub Handle

@manniL

### Project Name

Nuxt.js

### Project Repo

https://github.com/nuxt/nuxt/

### Stream Date

- [X] Yes
- [ ] Not yet

### Dates

03-08-2024

### Twitter URL

@TheAlexLichter

### LinkedIn URL

https://www.linkedin.com/in/alexanderlichter/

**Comment by AndreaGriffiths11** [comment]
Complete, thank you very much @manniL

**Comment by manniL** [comment]
Thanks for having me! Looking forward to joining again 🙌
