### ISSUE TITLE
Open Source Friday - NPM Ecosystem  - 03-22-2024

### ISSUE THREAD

**Issue by ljharb** [githubevents/open-source-friday#36]
### Name

Jordan Harband

### GitHub Handle

@ljharb

### Project Name

whatever would be most interesting

### Project Repo

https://github.com/ljharb/ljharb

### Stream Date

- [X] Yes
- [ ] Not yet

### Dates

03-22-2023

### Twitter URL

[@ljharb](https://twitter.com/ljharb)

### LinkedIn URL

https://linkedin.com/in/ljharb

### Additional Information

I maintain many projects, and I'm also on TC39 (the JS language specification committee). I'm happy to talk about one or many projects, and/or standardization work, and/or open source maintainer funding, and/or open source supply chain security :-)

**Comment by LadyKerr** [comment]
@ljharb thanks for opening up an issue! 

What project would you like to showcase r are most excited about? It's up to you! BUt just let us know which ones so it's easier to handle booking!

**Comment by AndreaGriffiths11** [comment]
@LadyKerr I'm unavailable to stream this wee, should we push this to a different date?

**Comment by ljharb** [comment]
@LadyKerr i never replied to this question, sorry :-)

What about if I talk about the cost of breaking changes in the npm ecosystem, and how that relates to open source sustainability?

(also I'm fine to reschedule if there's another day we can make work)

**Comment by AndreaGriffiths11** [comment]
@ljharb would you be open to pre-recording?

**Comment by ljharb** [comment]
@AndreaGriffiths11 definitely, lmk when works

**Comment by AndreaGriffiths11** [comment]
Streamyard link for recording: https://streamyard.com/nex23572n3

**Comment by ljharb** [comment]
Thanks, I had fun!
