### ISSUE TITLE
Open-Source Multiphysics Simulation Software - 04-05-24

### ISSUE THREAD

**Issue by akashdhruv** [githubevents/open-source-friday#39]
### Name

Akash Dhruv

### GitHub Handle

@akashdhruv 

### Project Name

Flash-X

### Project Repo

https://github.com/Flash-X
https://flash-x.org

### Stream Date

- [x] Yes
- [ ] Not yet

### Dates

04/05/2024

### LinkedIn URL

https://www.linkedin.com/in/akashdhruv

### Additional Information

Flash-X is an open-source simulation software instrument that models problems ranging from Astrophysics to Computational Fluid Dynamics by solving partial differential equations. 

The open-source model allows researchers all over the world to work with High Performance, Exascale capable code, contributing towards equity and integrity in scientific research.

Flash-X has Apache 2.0 license. 
```[tasklist]
### Tasks
```

**Comment by LadyKerr** [comment]
@akashdhruv are you still able to do the stream next week?

**Comment by akashdhruv** [comment]
@LadyKerr Yes. Please let me know if there anything you'd like me to prepare beforehand.

**Comment by LadyKerr** [comment]
![FlashX](https://github.com/githubevents/open-source-friday/assets/47188731/75060a48-278a-48c0-8c19-d75cb12af7cc)

**Comment by LadyKerr** [comment]
Stream Link: https://streamyard.com/wheik524kr

**Comment by LadyKerr** [comment]
Hey @akashdhruv this stream is scheduled for 10am central. I'm in Seattle recording and that's the time slot available for tomorrow, as I'm filming all day.

Hope that works for you!

Please see the stream guide for prep instructions: https://gist.github.com/LadyKerr/9b7d6dccde55b3f30398612d1290b7dc and would love a live demo on how to use the project locally and such. 

Should be a great stream! Super excited to learn more about this.

One thing - the code is private, folk will want to look at the code, can you add me to the repo and that's gonna be something we have to mention early and often. Open Source typically means the project is openly available for anyone to use it, so there may be some push back that they need to request access to see the open code.

Do add me to teh project, so I have links and such. Let me know if you have any questions.

**Comment by akashdhruv** [comment]
@LadyKerr Yes I can make 10 am work. I will add you the code repo. Even though the core code is private (due to DOE restrictions) it's still open source. Additionally, the demo that I am preparing will be public, so no issues there.

**Comment by akashdhruv** [comment]
@LadyKerr I have added you to the repository. Would it be ok if I prepare a short slide deck along with the demo to introduce the field of numerical simulations to a general audience?

**Comment by akashdhruv** [comment]
Demo repository: https://github.com/Lab-Notebooks/Opensource-Fridays-Demo

**Comment by LadyKerr** [comment]
@akashdhruv yes a deck is fine! just know the stream is about 35-40mins so everything should fit there!

**Comment by LadyKerr** [comment]
Hello @akashdhruv ! Im joining the stream now, please join if you're here! 
Linky: https://streamyard.com/wheik524kr
