### ISSUE TITLE
Open Source Friday - ClassroomIO - [02-02-2024]

### ISSUE THREAD

**Issue by rotimi-best** [githubevents/open-source-friday#40]
### Name

Rotimi Best

### GitHub Handle

@rotimi-best

### Project Name

ClassroomIO

### Project Repo

https://github.com/rotimi-best/classroomio

### Stream Date

- [X] Yes
- [ ] Not yet

### Dates

02-02-2024

### Twitter URL

https://twitter.com/rotimi_best

### LinkedIn URL

https://www.linkedin.com/in/best-r-7487b283/

**Comment by tobySolutions** [comment]
Looking forward to this!!

**Comment by rotimi-best** [comment]
@LadyKerr You bet I am 😃. Won't miss it for anything.

I just need to study the Preparation instructions to get prepared

**Comment by rotimi-best** [comment]
Hey @LadyKerr, would be possible for us to jump on a call maybe 30 minutes before to make sure my set up is good to go 😂.

Just worried so I don't screw something up 😅

**Comment by LadyKerr** [comment]
@rotimi-best yes of course! We'll be on the call 15mins before the start time to ensure everything is working well!

Also, for the demo, can you show how someone would create a new school? Would that be too much to show in a 20-30min demo?

**Comment by rotimi-best** [comment]
@LadyKerr That's great thanks.

I plan on showing how to create a course and publish it live in a school you create on ClassroomIO.com. 

Similar to this video: https://youtu.be/0i6CAuHsCTU

Creating a school happens when you sign up. However I can show a lot more when you want to create a course.

**Comment by LadyKerr** [comment]
that sounds great @rotimi-best ! Including some code would also be super dope!

**Comment by LadyKerr** [comment]
![Copy of OSF Thumbnails](https://github.com/githubevents/open-source-friday/assets/47188731/4d6f2f4a-bfda-4fdc-a0af-67ed886d6cfb)

**Comment by rotimi-best** [comment]
> that sounds great @rotimi-best ! Including some code would also be super dope!

Great. Do you mean showing the code behind it on a high level or a particular feature?

Not sure what part of the code to show.

**Comment by rotimi-best** [comment]
> ![Copy of OSF Thumbnails](https://private-user-images.githubusercontent.com/47188731/301286148-4d6f2f4a-bfda-4fdc-a0af-67ed886d6cfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MzExODAsIm5iZiI6MTcwNjczMDg4MCwicGF0aCI6Ii80NzE4ODczMS8zMDEyODYxNDgtNGQ2ZjJmNGEtYmZkYS00ZmRjLWEwYWYtNjdlZDg4NmQ2Y2ZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDE5NTQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhZDMzYmViYTliZDI4NGM1MmJmMTE0NWU5NjI0Y2MzMGM0OGMyMzM4ODIzZDk4YzJiZTAzYjRkMjEwOGFkYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mgzhkg6TH-0Abro5ijxWyiU0nn--cCWAw7eT87BGvEc)

This looks really good 😊

**Comment by LadyKerr** [comment]
Also here's a streaming guide to check out @rotimi-best 
https://gist.github.com/LadyKerr/9b7d6dccde55b3f30398612d1290b7dc

**Comment by rotimi-best** [comment]
> > > that sounds great @rotimi-best ! Including some code would also be super dope!
> > 
> > 
> > Great. Do you mean showing the code behind it on a high level or a particular feature?
> > Not sure what part of the code to show.
> 
> Maybe show how various lessons are managed? Any part of the code honestly LOL folks love seeing code on these streams - can choose something random - your choice

I see, alright. Will pick something.


> Also here's a streaming guide to check out @rotimi-best https://gist.github.com/LadyKerr/9b7d6dccde55b3f30398612d1290b7dc

Thank you 🙏

**Comment by rotimi-best** [comment]
Hi @LadyKerr , how do we get started on the stream?

**Comment by LadyKerr** [comment]
Hey @rotimi-best linky: https://streamyard.com/hjpwrp9fp4

**Comment by LadyKerr** [comment]
@rotimi-best That was REALLY GOOD!!

Yor project is amaaazing OMGG

Makes me wanna dig into svelte and supabase!

**Comment by LadyKerr** [comment]
Stream linky: https://www.linkedin.com/video/live/urn:li:activity:7158552335223242752/

**Comment by rotimi-best** [comment]
> @rotimi-best That was REALLY GOOD!!
> 
> Yor project is amaaazing OMGG
> 
> Makes me wanna dig into svelte and supabase!

Thank you @LadyKerr. I enjoyed every single bit of it. Hope we can do this some other time after we get our first 50 paying customers. 😊 😉
