### ISSUE TITLE
Open Source Friday - Homebrew - 05-03-2024

### ISSUE THREAD

**Issue by MikeMcQuaid** [githubevents/open-source-friday#41]
### Name

Mike McQuaid

### GitHub Handle

@MikeMcQuaid

### Project Name

Homebrew

### Project Repo

github.com/homebrew

### Stream Date

- [ ] Yes
- [X] Not yet

### Twitter URL

@MikeMcQuaid

### LinkedIn URL

https://www.linkedin.com/in/mkmcqd/

### Additional Information

Hey friends! Would love to find a date in December but couldn't see any from the picker yet. If it's out, no worries, let's do this in January!

**Comment by LadyKerr** [comment]
@MikeMcQuaid are you available Jan 5th 2024?

**Comment by MikeMcQuaid** [comment]
@LadyKerr My kids are home but: maybe! What sort of times? The week after is a lot more flexible. Dunno if your Calendly allows booking that far out but, if so, can take a look now. Thanks! ❤️

**Comment by LadyKerr** [comment]
@MikeMcQuaid hello Mike and happy new year!
We've been Out of office since that time so super apologies for super delayed response!

Turns out this week we're just ramping up and so the 5th actually won't work anymore. I have an open date on May 3rd, would that work for you? I know it's super far out LOL but folks have been grabbing the earlier spots.

**Comment by MikeMcQuaid** [comment]
@LadyKerr @AndreaGriffiths11 Happy New Year! May 3rd could work, what time? I’m in the U.K. and have kids so am fairly time sensitive. Can use a booking tool if you have one. If any earlier dates are free I’d love to have one! Also feel free to drop me a line if you have any last minute cancellations. Can email or iMessage me at mike@mikemcquaid.com. Thanks!

**Comment by LadyKerr** [comment]
@MikeMcQuaid usually around 12pm CST which is around 6pm UK time?

What time would work for you? Give me 3 options and maybe we can have the stream at a diff time that day!

**Comment by MikeMcQuaid** [comment]
@LadyKerr Have Booked May 3rd, thanks!

**Comment by MikeMcQuaid** [comment]
@AndreaGriffiths11 didn't see it! can you resend to mike@workbrew.com? Thanks ❤️

**Comment by MikeMcQuaid** [comment]
@AndreaGriffiths11 Got it, thanks!
