### ISSUE TITLE
Open Source Friday - Grafana - 08-23-24

### ISSUE THREAD

**Issue by codeincarnate** [githubevents/open-source-friday#42]
### Name

Kyle Cunningham

### GitHub Handle

codeincarnate

### Project Name

Grafana

### Project Repo

[github.com/grafana/grafana](https://github.com/grafana/grafana)

### Stream Date

- [X] Yes
- [ ] Not yet

### Dates

04-26-2024

### LinkedIn URL

https://www.linkedin.com/in/codeincarnate

### Additional Information

 The Github Grafana plugin is a powerful tool for observing ongoing development, planning, and operations on Github. In this talk, we’ll show how this plugin along with other powerful tools from the Grafana toolbox can help supercharge the Github development workflow.

**Comment by LadyKerr** [comment]
Hey @codeincarnate didn't hear from you so have to cancel this stream. 
If you want to get on the show again, feel free to reach out!

**Comment by LadyKerr** [comment]
Hey @codeincarnate this stream is scheduled for 8/23. Does that date still work for you?

**Comment by codeincarnate** [comment]
@LadyKerr it does! Looking forward to speaking 😄

**Comment by LadyKerr** [comment]
Event linky: https://gh.io/grafanalabs

Stream link: https://streamyard.com/97763bck3g

![Image](https://github.com/user-attachments/assets/14b79df9-bdeb-46ac-b7fa-6d356b30d534)

**Comment by LadyKerr** [comment]
@codeincarnate event is scheduled! Looking forward to seeing the product in action with a live dem and just chatting!

**Comment by codeincarnate** [comment]
Thank you @LadyKerr! I'm looking forward to this 😄

**Comment by LadyKerr** [comment]
Hey @codeincarnate are you joining soon? haha

**Comment by LadyKerr** [comment]
Thanks so much for joining @codeincarnate !!
