### ISSUE TITLE
Open Source Friday - [LIDA] - [02-16-2024]

### ISSUE THREAD

**Issue by victordibia** [githubevents/open-source-friday#43]
### Name

Victor Dibia

### GitHub Handle

@victordibia

### Project Name

LIDA - Automatic Generation of Visualizations and Infographics using Large Language Models

### Project Repo

https://github.com/microsoft/lida

### Stream Date

- [x] Yes
- [ ] Not yet

### Dates

02-16-2024

### Twitter URL

@vykthur

### LinkedIn URL

https://www.linkedin.com/in/dibiavictor/

## Abstract

Systems that support users in the **automatic creation of visualizations** must address several subtasks - understand the semantics of data, enumerate relevant visualization goals and generate visualization specifications.  
LIDA, is a tool for generating visualizations and infographics. LIDA comprises of 4 modules - A SUMMARIZER that converts data into a rich but compact natural language summary, a GOAL EXPLORER that enumerates visualization goals given the data, a VISGENERATOR that generates, refines, executes and filters visualization code and an INFOGRAPHER module that yields data-faithful stylized graphics using IGMs.

LIDA provides a python api, a web api and a hybrid user interface (direct manipulation and multilingual natural language) for interactive chart, infographics and data story generation. 

```bash
pip install lida
```

```python
from lida import Manager

lida = Manager()
summary = lida.summarize("data/cars.json") # generate data summary 
goals = lida.goals(summary, n=5, persona="ceo with aerodynamics background") # generate goals
# generate charts (generate and execute visualization code)
charts = lida.visualize(summary=summary, goal=goals[0], library="matplotlib") # seaborn, ggplot ..
```

![Image](https://github.com/githubevents/open-source-friday/assets/1547007/afc907d4-5e47-41d1-bd04-782c009b354e)

**Comment by LadyKerr** [comment]
![Copy of OSF Thumbnails (1)](https://github.com/githubevents/open-source-friday/assets/47188731/b4daf2bc-0a36-44c5-a684-908200988efd)

**Comment by LadyKerr** [comment]
Social post scheduled for Thursday!

**Comment by LadyKerr** [comment]
@victordibia streamyard link is here: https://streamyard.com/ibdwc75x4m
