### ISSUE TITLE
Open Source Friday - [Million.js] - 04-12-2024

### ISSUE THREAD

**Issue by tobySolutions** [githubevents/open-source-friday#44]
### Name

Aiden Bai, Tobiloba Adedeji

### GitHub Handle

@aidenybai, @tobySolutions

### Project Name

Million.js

### Project Repo

https://github.com/aidenybai/million

### Stream Date

- [X] Yes
- [ ] Not yet

### Dates

04-12-2024

### Twitter URL

@toby_solutions, @aidenybai

### LinkedIn URL

https://www.linkedin.com/in/tobiloba-adedeji/, https://www.linkedin.com/in/aidenbai/

### Additional Information

Million.js is a fast and lightweight (<4kb) virtual DOM that can improve React's speed by up to 70%. With a fine-tuned, optimized virtual DOM, Million.js can have your React components running at the speed of raw JavaScript.

Million now also has an AI assistant that helps you write more performant React and Next code called [MillionAI](https://million.dev/ai)

**Comment by AndreaGriffiths11** [comment]
Thank you @tobySolutions for your support and flexibility, we'll be pre-recording this stream on 4-4

**Comment by tobySolutions** [comment]
Thank you @AndreaGriffiths11, can we do Tuesday please? Thank you! 

Also, can you add Aiden Bai's email? (aiden.bai05@gmail.com)

<img width="857" alt="Screenshot 2024-03-30 at 13 23 33" src="https://github.com/githubevents/open-source-friday/assets/96334363/59c9fd90-cc6f-41bd-aeea-ecf9c6035b73">

**Comment by AndreaGriffiths11** [comment]
Done! Looking forward to meeting ✨

**Comment by tobySolutions** [comment]
> Done! Looking forward to meeting ✨

Awesome! Thank you very much, Andrea!

**Comment by AndreaGriffiths11** [comment]
Closing until further reschedule
