### ISSUE TITLE
Open Source Friday - Uli - 07-12-2024 Pre-record to air in IST friendly time same date

### ISSUE THREAD

**Issue by csmlo** [githubevents/open-source-friday#46]
### Name

Denny George

### GitHub Handle

@dennyabrain

### Project Name

Uli

### Project Repo

https://github.com/tattle-made/Uli

### Stream Date

- [x] Yes
- [ ] Not yet

### Dates

07-05-2024

### LinkedIn URL

https://www.linkedin.com/in/denny-george-4097bb33/?originalSubdomain=in

### Additional Information

Reclaim your online space!
Use Uli to redact slurs and abusive content, archive problematic content, and collectively push back against online gender based violence on social media in India through a browser extension which is supported on Chrome, Brave and Firefox. 

Uli is a browser plugin that :

- De-normalizes the everyday violence that people of marginalized genders experience online in India
- Provides tools for relief and collective response.
- It is an attempt to invert the top-down logics of platform moderation and center the experiences of those subject to online gender-based violence.

**Comment by AndreaGriffiths11** [comment]
Hi @dennyabrain, could you please email me at andreagriffiths11@github.com to coordinate

**Comment by dennyabrain** [comment]
hi @AndreaGriffiths11 sent you an email just now.

**Comment by AndreaGriffiths11** [comment]
Inivation sent to pre-record, thanks for the flexibility @dennyabrain

**Comment by kaustubhavarma** [comment]
Hi! This is my preferred image: ![IMG_6793](https://github.com/githubevents/open-source-friday/assets/136114974/9c4932b1-ae2c-4101-9e32-542ab7d901ea)

My bio: Kaustubha is the program manager for Uli and counsel at Tattle Civic Tech. She is an India-qualified lawyer who has worked extensively in the field of technology law and policy on matters relating to online gender based violence (OGBV), artificial intelligence, platform governance and open source software in India. 

My LinkedIn: https://www.linkedin.com/in/kaustubhakalidindi/

**Comment by dennyabrain** [comment]
My Bio :  Denny George is Co Founder and Tech Lead at Tattle Civic Tech. His work engages with complex socio-technical problems using software and humour. His creative practice is composed of prototyping and building technology to imagine and present solutions for these issues.

**Comment by AndreaGriffiths11** [comment]
Thanks again @dennyabrain and @kaustubhavarma, I appreciate your time and we are very excited to publish the interview. Air date has changed to prevent conflict with an internal event, new air date will be July 12th, 2024 at 1200 IST.
Here is the updated Meetup event: https://www.meetup.com/github/events/301779843/?slug=github&eventId=301779843

**Comment by dennyabrain** [comment]
@AndreaGriffiths11 noted. thank you. will look forward to the release.

**Comment by dennyabrain** [comment]
@AndreaGriffiths11 this did not air, right?

**Comment by AndreaGriffiths11** [comment]
Hey Denny, yes it did. Here is the link to the stream in YouTube 
https://www.youtube.com/live/IjNVoAyKYeY?feature=shared

**Comment by dennyabrain** [comment]
aah my bad. I was looking directly on youtube under the open source friday playlist. Thank you!
