### ISSUE TITLE
Open Source Friday - if-me.org - airs 10-4-2024

### ISSUE THREAD

**Issue by csmlo** [githubevents/open-source-friday#47]
### Name

Julia Nguyen

### GitHub Handle

@julianguyen

### Project Name

if-me.org

### Project Repo

https://github.com/ifmeorg/ifme

### Stream Date

- [x] Yes
- [ ] Not yet

### Dates

06-07-2024

### LinkedIn URL

https://www.linkedin.com/in/nguyenjulia/?originalSubdomain=ca

### Additional Information

if-me.org is a community for mental health experiences that encourages people to share their personal stories with trusted allies. It is an open source mental health communication app to share stories with loved ones. 
Trusted allies are the people we interact with on a daily basis, including friends, family members, co-workers, teachers, and mental health workers. Dealing with mental health is what makes all of us human. 

If-me.org is open source because mental health should be open.

**Comment by AndreaGriffiths11** [comment]
@csmlo could you please DM us @julianguyen 's email

**Comment by AndreaGriffiths11** [comment]
### 8/16 Update

Emailed Julia about rescheduling

**Comment by AndreaGriffiths11** [comment]
Complete: [stream](https://www.linkedin.com/video/live/urn:li:ugcPost:7248014139342688256/)
