### ISSUE TITLE
Open Source Friday - Open Source Design - 9-20-24

### ISSUE THREAD

**Issue by Erioldoesdesign** [githubevents/open-source-friday#48]
### Name

Eriol Fox

### GitHub Handle

@erioldoesdesign

### Project Name

opensourcedesign.net

### Project Repo

https://github.com/opensourcedesign

### Stream Date

- [X] Yes
- [ ] Not yet

### Dates

06/21/2024

### Twitter URL

@erioldoesdesign

### LinkedIn URL

https://www.linkedin.com/in/eriolfox/

### Additional Information

I'm not sure how to apply to speak? I wonder if you'd like to have open source design folks speak on the open fridays?

**Comment by LadyKerr** [comment]
@Erioldoesdesign can you tell me more about Open Source Design?

**Comment by Erioldoesdesign** [comment]
> @Erioldoesdesign can you tell me more about Open Source Design?

for sure! 

So Open Source Design's creation pre-dates my maintainer involvement by around 5 years. The project/community has been around 'formally' (as in, with a visible web presence) for over 10 years. The main activities of Open Source Design are:

1. Be a community space for designers (and developers + others!) to find other people thinking about the design (broadly) of open source software to discuss, support and offer/receive help and advice. We aim to be that first contact community when a person thinks 'What about the design aspects of OSS? Who does that and how is it done?'

2. Hold specific space at events like FOSDEM and FOSSBackstage where we apply for devrooms and conference tracks for design and usability speakers working in the OSS space to speak to the wider OSS community and for non-designers to speak about how they understand and approach design. We also hold design/UX/usability clinics at events for ‘drop in’ advice sessions for OSS maintainers.

3. Maintain a jobs page where OSS projects looking for design contributions can post their projects and gain contribution or hire designers as paid workers.

We do lots more as individuals and the organisations we work with/for but this is just a snap shot 😄

**Comment by LadyKerr** [comment]
Awesome! Can you select the 17th on this calendar: https://calendar.app.google/rTSXKtyHf1FbxBDL9 This way you'll be all set for the 17th! @Erioldoesdesign

**Comment by Erioldoesdesign** [comment]
> Awesome! Can you select the 17th on this calendar: https://calendar.app.google/rTSXKtyHf1FbxBDL9 This way you'll be all set for the 17th! @Erioldoesdesign

Done! 

Any chance I can invite other OSD community members too? @saptaks and @jdittrich are interested in joining :)

**Comment by LadyKerr** [comment]
Hey @Erioldoesdesign !

Sadly we need to reschedule this session. Are you available on June 21st?

**Comment by Erioldoesdesign** [comment]
> Hey @Erioldoesdesign !
> 
> Sadly we need to reschedule this session. Are you available on June 21st?

Yes I am :)

**Comment by LadyKerr** [comment]
Awesome! thank you!
You should be able to add other guests to the invte I just sent!

@Erioldoesdesign

**Comment by LadyKerr** [comment]
Hey @Erioldoesdesign apologies for unresponsiveness and delays and such.
Ive been traveling a tonn for work and had to take some time off, so sadly this stream needs to be moved back until when I get back in office. Sorry about the late response and the last minute cancellation

**Comment by Erioldoesdesign** [comment]
> Hey @Erioldoesdesign apologies for unresponsiveness and delays and such. Ive been traveling a tonn for work and had to take some time off, so sadly this stream needs to be moved back until when I get back in office. Sorry about the late response and the last minute cancellation.
> 
> You may have gotten an auto-decline message from my calendar

No worries - life happens and I'm totally good to re-sched for when life is less busy for you.

**Comment by LadyKerr** [comment]
Hey @Erioldoesdesign! Im finally back in office and would LOVE to reschedule this episode.

Can you let me know if any date in Sept works for ya?

**Comment by Erioldoesdesign** [comment]
> Hey @Erioldoesdesign! Im finally back in office and would LOVE to reschedule this episode.
> 
> Can you let me know if any date in Sept works for ya?

How does the 3rd, 5th or 6th of sept work? I can make most times those days though i'm in UK timezone

**Comment by AndreaGriffiths11** [comment]
@LadyKerr I can confirm Sep 6th here, if that still works with @Erioldoesdesign

**Comment by Erioldoesdesign** [comment]
> @LadyKerr I can confirm ~Sep 6th here~ Sep 20th, if that still works with @Erioldoesdesign

Sept 20th works for me - please do send over a calendar invite to eriol@superbloom.design

**Comment by LadyKerr** [comment]
streamed!
√https://www.youtube.com/watch?v=Kx_fIIBzaQE
