### ISSUE TITLE
Open Source Friday - Octokit - 04-19-2024

### ISSUE THREAD

**Issue by kfcampbell** [githubevents/open-source-friday#49]
### Name

Keegan Campbell

### GitHub Handle

@kfcampbell

### Project Name

Octokit

### Project Repo

github.com/octokit](https://github.com/octokit)

### Stream Date

- [x] Yes
- [ ] Not yet

### Dates

04-19-2024

### Twitter URL

N/A

### LinkedIn URL

https://www.linkedin.com/in/kfcampbell/

### Additional Information

@nickfloyd will be with me! His Twitter URL is https://twitter.com/nickfloyd and his LinkedIn URL is https://www.linkedin.com/in/nickfloyd/.

**Comment by LadyKerr** [comment]
@kfcampbell @nickfloyd are you still available for next week's stream? Super stoked for this one!

**Comment by nickfloyd** [comment]
Hey @LadyKerr, I'll be there ❤!

**Comment by kfcampbell** [comment]
You bet! I'm pumped.

**Comment by LadyKerr** [comment]
Event link: https://gh.io/octokit



![OSF-Octokit](https://github.com/githubevents/open-source-friday/assets/47188731/0a73db1e-b446-424d-a37b-d2b658052ce1)

**Comment by LadyKerr** [comment]
@kfcampbell @nickfloyd Jic you missed the streaming guide above, here is the link again: https://gist.github.com/LadyKerr/9b7d6dccde55b3f30398612d1290b7dc 

Be sure to have a lil demo prepped for the stream as well! Folks love to dig into code - would be great to show how to start using one of the SDK's and such. We'll just be chatting about the work you do so no pressure!

Let me know if you have any questions (ping me on slack)

Chat soon! 💃🏼
