### ISSUE TITLE
Open Source Friday - Chayn - 05-10-2024

### ISSUE THREAD

**Issue by csmlo** [githubevents/open-source-friday#50]
### Name

Ellie Re'em and Kylee Fields

### GitHub Handle

@eleanorreem and @kyleecodes

### Project Name

Chayn

### Project Repo

https://github.com/chaynHQ/bloom-frontend

### Stream Date

- [x] Yes
- [ ] Not yet

### Dates

05-10-2024

### Additional Information

Chayn (pronounced 'ch-en') meaning “solace” in Urdu. ☀️

Chayn is an award-winning, global nonprofit, run by survivors and allies from around the world, creating resources to support healing from gender-based violence.

We specialize in open-source digital public goods and services for survivors of abuse that are trauma-informed, intersectional, multi-lingual and feminist.

In 2023, Chayn partnered with GitHub's Social Impact team for the [Digital Public Goods Open Source Community Manager Program](https://socialimpact.github.com/tech-for-social-good/dpg-open-source-community-manager-program).

Learn more about us: https://org.chayn.co/
Explore our projects: https://org.chayn.co/projects
Read our research and how Chayn has made an impact: https://org.chayn.co/research

Learn how Chayn supports survivors of gender-based violence through open source! Chayn is an global nonprofit, run by survivors and allies from around the world, creating open resources to support the healing of survivors of gender-based violence.

**Comment by LadyKerr** [comment]
Hi @eleanorreem and @kyleecodes! Confirming that this Friday is still good for you, for the stream?
cc: @csmlo

**Comment by kyleecodes** [comment]
Hey @LadyKerr! Yes we are good to go for Friday. Is it still at 1pm Eastern time?
Also it will just be me speaking. Looking forward to it!

**Comment by LadyKerr** [comment]
Hey @kyleecodes thanks for letting me know and awesome!! I'll create the show assets and schedule then!
Lemme know if you have queries!

**Comment by LadyKerr** [comment]
Hey @kyleecodes will you be presenting a technical demo during the stream?
Typically there is a demo on how to use the app and how folks can get started doing something small, or showing off the tech/code that it's built with. 

Wanted to double check on that

**Comment by LadyKerr** [comment]
![chayn_stream](https://github.com/githubevents/open-source-friday/assets/47188731/ae40235c-dfce-4c22-8531-f34f600f5411)

**Comment by kyleecodes** [comment]
Hey @LadyKerr, yes I can confirm I can do the demo. 
Thank you for the preparation instructions, I appreciate how clear and concise it is! I will let you know if I have any questions. 
Also, love this graphic!
Thanks again, and looking forward to it!

**Comment by LadyKerr** [comment]
Hey @kyleecodes I tried to guess your email LOL
Added you to the invite - maybe wrong email addy (dont add to issue)

But here is the streamlink: https://streamyard.com/iajmr4ektx

**Comment by LadyKerr** [comment]
Hey @kyleecodes please join like 10 mins before the stream start time!
