### ISSUE TITLE
Open Source Friday - Marlin Firmware - 5-24-2024

### ISSUE THREAD

**Issue by thinkyhead** [githubevents/open-source-friday#52]
### Name

Scott Lahteine

### GitHub Handle

@thinkyhead

### Project Name

Marlin Firmware

### Project Repo

github.com/MarlinFirmware/Marlin

### Stream Date

- [X] Yes
- [ ] Not yet

### Dates

5-24-2024

### Twitter URL

@MarlinFirmware

### LinkedIn URL

linkedin.com/in/thinkyhead/

### Additional Information

First released in late 2011, Marlin Firmware quickly grew to become one of the most popular and versatile drivers for 3D printers and has played a vital role in the expansion of consumer 3D printing. Originally born out of the RepRap Project and targeting Arduino micro-controllers, over the last 12 years hundreds of developers and makers of 3D printers from around the world have contributed components and improvements.

We face increasing competition from things like Klipper firmware and closed-source Bambu printers, but these products serve a different niche. Marlin is designed to be very efficient so it can run on any self-contained board with a single MCU and enough I/O, so while the industry is focusing on Linux-based solutions today, the power and potential of single-board printers is limitless, especially as processors continue to get more powerful.

Around 2012 I started out as a part-time contributor, and my job soon evolved into lead developer and maintainer. By 2014 this project had become a full-time job, and today I'm supported entirely by donations from Patreon and GitHub Sponsors.

In my daily routine, I spend time integrating patches and new features, coordinating testing, working on refactors, deciding when to tag new releases, and so on. I try to educate myself about the platforms, components, and technologies that this project targets, but I depend on other knowledgeable nerds for many aspects.

The project depends on many other open source projects like PlatformIO and Arduino libraries, and it wouldn't be nearly as doable without having GitHub as a resource. We also use GitHub to maintain Documentation, Configurations, libraries, a VSCode extension, and even a Simulator to run Marlin on the desktop for testing.

**Comment by AndreaGriffiths11** [comment]
Hiya @thinkyhead, please note the new date for the stream, if this day doesn't work, please let us know and thank you again for being a part of #opensourcefriday

**Comment by thinkyhead** [comment]
May 24 should be just fine, thanks!

**Comment by AndreaGriffiths11** [comment]
Hi @thinkyhead I've sent you an email to ask if you'd be available to prerecord next week?

**Comment by thinkyhead** [comment]
Hi @AndreaGriffiths11 — Life has had me in a tizzy this week. I'll complete the above tasks and reply to your email shortly….

**Comment by thinkyhead** [comment]
Hello again @AndreaGriffiths11 and happy Wednesday. I can't find your email in my INBOX (and didn't see it in the SPAM folder either). So anyway, I do have some basic questions not addressed by the linked document. As for the rest of the guide, I can be prepared for recording this week and I'll prepare a 5-10 minute demo of Marlin in action, starting and controlling a print job.

My questions regard the preparation steps listed above:

- What kind of "social card" should I be creating? Is this a feature of GitHub or Twitch?
- Where do I create the "meetup link"? (I assume this does not refer to Meetup dot com.)
- I can create/schedule a Twitch stream and announce it on Linkedin and Twitch. (Simulcasting to YouTube is not possible.) What date and time should I set for this stream?
- The same question applies for the social media post (Twitter). I presume that I should schedule it for the broadcast date (May 24), not the recording date (presumably, May 17), correct?

Anyway, I look forward to showing off my project and having a chance to say "thanks" publicly to GitHub for making it possible. TTYL!

**Comment by AndreaGriffiths11** [comment]
Hiya @thinkyhead so sorry for the confusion, those todo's are for me! Would you mind sending me an email andreagriffiths11@gmail.com or replying to me on LinkedIn so we can coordinate

**Comment by AndreaGriffiths11** [comment]
Thanks again Scott for your time!
