### ISSUE TITLE
Open Source Friday - Maybe Finance - 01-19-2024

### ISSUE THREAD

**Issue by LadyKerr** [githubevents/open-source-friday#54]
### Name

 Josh Pigford

### GitHub Handle

@Shpigford

### Project Name

Maybe Finance

### Project Repo

https://github.com/maybe-finance/maybe

### Stream Date

- [x] Yes
- [ ] Not yet

### Dates

01-19-2024

### Twitter URL

https://twitter.com/Shpigford

**Comment by LadyKerr** [comment]
![osf_maybefinance](https://github.com/githubevents/open-source-friday/assets/47188731/ab3b0105-a046-43b8-8656-1f3d13222da0)

**Comment by LadyKerr** [comment]
Stream Link JIC: https://streamyard.com/cw3tnfbqq6 

Streaming on Streamyard

**Comment by Shpigford** [comment]
Looking good! What's the link I should share ahead of time on Twitter?

**Comment by LadyKerr** [comment]
@Shpigford you can share the youtube link: https://www.youtube.com/watch?v=Swf4IbGy-3c&ab_channel=GitHub folks can set reminders. 
Official comms goes out tomorrow on twitter
