### ISSUE TITLE
Open Source Friday - Uli - 07-05-24

### ISSUE THREAD

**Issue by dennyabrain** [githubevents/open-source-friday#55]
### Name

Denny George

### GitHub Handle

@dennyabrain

### Project Name

Uli

### Project Repo

https://github.com/tattle-made/uli

### Stream Date

- [X] Yes
- [ ] Not yet

### Dates

07-05-2024

### Twitter URL

@dennymades

### LinkedIn URL

https://www.linkedin.com/in/denny-george-4097bb33/

### Additional Information

The scope of building tech and resources for content moderation in Indian language is huge. Successfully covering various use cases and languages assumes heavy participation from the community. Uli could make use of contributions of code, translations, annotations etc. We can talk about how we tried to address these, where we succeeded and failed. Anchoring this discussion on Uli's process we can talk broadly about how this applies to creating Responsible AI projects using principles from FOSS.

**Comment by AndreaGriffiths11** [comment]
TRacking in: https://github.com/githubevents/open-source-friday/issues/46
