### ISSUE TITLE
Open Source Friday - if-me.org - 06-07-24

### ISSUE THREAD

**Issue by julianguyen** [githubevents/open-source-friday#60]
### Name

Julia Nguyen

### GitHub Handle

@julianguyen

### Project Name

if-me.org

### Project Repo

github.com/ifmeorg/ifme

### Stream Date

- [ ] Yes
- [ ] Not yet

### Dates

06-07-2024

### Twitter URL

twitter.com/ifmeorg

### LinkedIn URL

https://www.linkedin.com/in/nguyenjulia/

**Comment by AndreaGriffiths11** [comment]
Tracking in https://github.com/githubevents/open-source-friday/issues/47
