### ISSUE TITLE
Open Source Friday - UPPTIME - 03-01-2024

### ISSUE THREAD

**Issue by LadyKerr** [githubevents/open-source-friday#64]
### Name

Anand Chowdhary

### GitHub Handle

@AnandChowdhary

### Project Name

UPPTIME

### Project Repo

https://github.com/upptime/upptime

### Stream Date

- [X] Yes
- [ ] Not yet

### Dates

03-01-2024

### Twitter URL

@itsthatladydev

### LinkedIn URL

https://www.linkedin.com/in/kedashakerr/

### Additional Information

Upptime (https://upptime.js.org/) is the open-source uptime monitor and status page, powered entirely by GitHub Actions, Issues, and Pages. It's made with 💚 by [Anand Chowdhary](https://anandchowdhary.com/), supported by [Pabio](https://pabio.com/).

**Comment by LadyKerr** [comment]
@AnandChowdhary are you still down for Open Source Friday this Friday?

Looking forward to having you!

**Comment by AnandChowdhary** [comment]
Yes, ma'am! Looking forward!

**Comment by LadyKerr** [comment]
![Upptime](https://github.com/githubevents/open-source-friday/assets/47188731/1df18825-0951-495f-9482-6ca3eeac30a7)

**Comment by LadyKerr** [comment]
@AnandChowdhary would love to have a live demo on how to integrate Upptime in an application! Do let me know if you have any questions before the stream. It's all scheduled and a tweet goes out tomorrow.

The stream guide [is here](https://github.com/githubevents/open-source-friday/blob/main/admin/guest-assets/Streaming-Guide.md) if you need it! 

Looking forward! 🚀

**Comment by AnandChowdhary** [comment]
Fantastic, I'll prepare the demo as well, looking forward!

Quick question: Do I need to install any additional software to make it work? Or is Streamyard browser-based and I can just log in and everything should work?

**Comment by LadyKerr** [comment]
@AnandChowdhary streamyard is a login and just works. No need to download any additional software!

**Comment by LadyKerr** [comment]
Streamyard linky: https://streamyard.com/qxc42fkjam
@AnandChowdhary
