### ISSUE TITLE
Open Source Friday - Open Terms Archive- pending new date

### ISSUE THREAD

**Issue by MattiSG** [githubevents/open-source-friday#65]
### Name

Matti Schneider

### GitHub Handle

@MattiSG

### Project Name

Open Terms Archive

### Project Repo

https://github.com/OpenTermsArchive/

### Stream Date

- [X] Yes
- [ ] Not yet

### Dates

06-28-2024

### Twitter URL

@OpenTerms

### LinkedIn URL

https://www.linkedin.com/company/100378979/

**Comment by AndreaGriffiths11** [comment]
Hey @LadyKerr this will need to be prerecorded

**Comment by AndreaGriffiths11** [comment]
Please email andreagriffiths11@github.com to schedule
