### ISSUE TITLE
Open Source Friday - GitHub CLI & Copilot in the CLI - 9-13-24

### ISSUE THREAD

**Issue by LadyKerr** [githubevents/open-source-friday#66]
### Name

Andy Feller

### GitHub Handle

@andyfeller

### Project Name

GitHub Copilot in the CLI

### Project Repo

https://github.com/github/gh-copilot

### Stream Date

- [X] Yes
- [ ] Not yet

### Dates

05-31-2024

### Additional Information

Showcasing Copilot in the CLI and also GitHub CLI generally!
CC: @mxie 

Need engineer's names for GitHub CLI to add to invite

**Comment by andyfeller** [comment]
**@LadyKerr : How and what might William Martin (@williammartin) and I prepare ahead of time?**

With a little over a month, I'd feel better knowing we came prepared to talk about aspects or topics that the audience is particularly interested in.

**Comment by williammartin** [comment]
I'm sorry what is this? This is the first I'm hearing of this.

**Comment by LadyKerr** [comment]
Hey team @andyfeller @williammartin need to recshedule this one as Im OOO that day - on a well needed break.

I'll reschedule this when I get back and we can actually talk about pre-recordings!

**Comment by LadyKerr** [comment]
Hey team!
How about August 9th for this stream?
We could do a live stream on that date or we could do a pre-recorded video

@andyfeller @williammartin

**Comment by williammartin** [comment]
I'm on vacation from 29th July to 14th August so I cannot do it live. I am happy to pre-record something if that's preferable though.

**Comment by williammartin** [comment]
Are we looking to do something here? I'm quickly running out of time with regards vacation. I don't really have any indication of what we would be demo-ing here. Is it up to us? How long would it be? Is there written guidance anywhere on producing a video?

**Comment by LadyKerr** [comment]
Hey @williammartin let's table this for when you're back from vacation.
I've been out and been traveling as well hence the lack of communication and clarity here in this issue, my apologies. 

Let's get this on the schedule for when you're back.

For more context, Open Source Friday is a weekly tech stream where we showcase open source projects. The maintainers come on and talk about what they built and show the audience how to get started with the app and any other cool features they want to show off.

For gh cli specifically, you would show installing and using gh cli in addition to using gh copilot in the cli. 
Here is an example stream you can reference: https://www.youtube.com/watch?v=EKlKHl6i5m4

**Comment by LadyKerr** [comment]
Tentative new date Sept 13th!

**Comment by andyfeller** [comment]
Thanks, @LadyKerr! I think that works with @williammartin being back from vacation and before any other out of office leave.  

cc: @mxie

**Comment by LadyKerr** [comment]
Stream Link: https://streamyard.com/f2bq6e6myd

**Comment by LadyKerr** [comment]
Stream recorded and scheduled for 9/13!
