### ISSUE TITLE
Open Source Friday - Sprout - pending new date

### ISSUE THREAD

**Issue by tobySolutions** [githubevents/open-source-friday#68]
### Name

 Gui Bibeau, Tobiloba Adedeji

### GitHub Handle

@tobySolutions, @GuiBibeau

### Project Name

Sprout

### Project Repo

https://github.com/GuiBibeau/sprout

### Stream Date

- [X] Yes
- [ ] Not yet

### Dates

07-26-2024

### Twitter URL

@toby_solutions, @GuiBibeau

### Additional Information

This project is an open-source alternative to OpenAI's Assistant API. It provides a powerful, flexible AI model for generating human-like text based on the input provided.

**Comment by tobySolutions** [comment]
The workflow for this issue keeps failing. Can you please help check this out @AndreaGriffiths11, @LadyKerr 🙏. Thank you.

**Comment by LadyKerr** [comment]
Hey @tobySolutions wanted to check with you that this date is still good?

**Comment by tobySolutions** [comment]
> Hey @tobySolutions wanted to check with you that this date is still good?

Yes, it is perfect!!! We're a go for that day!!

**Comment by LadyKerr** [comment]
Hey @tobySolutions wanted to confirm for next week again!

**Comment by tobySolutions** [comment]
> Hey @tobySolutions wanted to confirm for next week again!

Hey @LadyKerr, sorry, but I sent in a mail last week that I am not sure you got; my bad. The team had to cancel due to issues with our project not having a ready enough demo yet. 

We agreed on a decision to come back on when we had something that we feel comfortable to demo on the show.

**Comment by LadyKerr** [comment]
Hey @tobySolutions thanks for letting me know!
