### ISSUE TITLE
Open Source Friday - [@idrinth/api-bench] - [08-02-2024]

### ISSUE THREAD

**Issue by Idrinth** [githubevents/open-source-friday#69]
### Name

Björn Büttner

### GitHub Handle

@Idrinth

### Project Name

@idrinth/api-bench

### Project Repo

https://github.com/idrinth/api-bench

### Stream Date

- [X] Yes
- [ ] Not yet

### Dates

08-02-2024

### Twitter URL

@idrinth

### LinkedIn URL

https://www.linkedin.com/in/bjoern-idrinth-buettner/

### Additional Information

The project is a mono-repo written almost completely in typescript. It serves as my go to solution for testing apis with little coding required, no matter if we are talking about performance tests or integration tests.
The project is about four years old and has suddenly spiked towards the end of last year, so the need for and maturity of the code base seem to have grown noticeably.

I would be very happy about talking about how to deal with a sudden growth like that, since I believe it will be interesting to maintainers and contributors on github.

Currently we focus on making the results easier to track and monitor while adding even more default checks to reduce the coding need. The hope is, that my contributors and me grow a bit more personally and that we can help others save their Developer Experience when trying to test apis.

**Comment by Idrinth** [comment]
Still on, looking forward to chat!

**Comment by Idrinth** [comment]
A few things that happened in between:
- we moved to an org with separate repositories ( https://github.com/idrinth-api-bench ), splitting the mono-repo
- we published npm packages under the new org name, including translation and react improvement packages ones we needed

**Comment by LadyKerr** [comment]
ok cool! I will schedule the stream!

**Comment by LadyKerr** [comment]
![Image](https://github.com/user-attachments/assets/940ffb88-086b-4045-968a-19b532ea5801)

**Comment by LadyKerr** [comment]
Ok stream is scheduled!

@Idrinth here is the stream link: https://streamyard.com/qnzi7iae9f 
I had to push back the show by 15minutes, so please join at 12pm central/7pm Germany time (I think!)

Lemme know if you have questions! Should be a good chat

**Comment by Idrinth** [comment]
no problem at all, will be there on time

**Comment by LadyKerr** [comment]
Thanks for joining @Idrinth
