### ISSUE TITLE
Open Source Friday - mirrord - 09-06-2024

### ISSUE THREAD

**Issue by Anita-ihuman** [githubevents/open-source-friday#71]
### Name

Eyal Bukchin

### GitHub Handle

@eyalb181

### Project Name

mirrord

### Project Repo Link

https://github.com/metalbear-co/mirrord

### Stream Date

- [X] Yes
- [ ] Not yet

### Twitter URL

@EBukchin

### LinkedIn URL

https://www.linkedin.com/in/eyal-bukchin

### Additional Information

mirrord is an open-source tool that lets developers run local processes in the context of their cloud environment. It simplifies the development, testing, and debugging of Kubernetes cluster without the complexities of Dockerization, CI/CD pipelines, or deployments.

**Comment by Anita-ihuman** [comment]
@AndreaGriffiths11 I would like to follow up with this session. 
Do I need to make anything available, or an abstract?

**Comment by LadyKerr** [comment]
Hey @Anita-ihuman this session is scheduled for next week!! We're looking forward to it!

**Comment by Anita-ihuman** [comment]
> Hey @Anita-ihuman, this session is scheduled for next week!! We're looking forward to it!

Thank you.

**Comment by LadyKerr** [comment]
Hey @Anita-ihuman is it you or @eyalb181 that'll be on stream?

**Comment by Anita-ihuman** [comment]
@

> Hey @Anita-ihuman is it you or @eyalb181 that'll be on stream?

@eyalb181 will be the speaker

**Comment by eyalb181** [comment]
Hey @LadyKerr , was I supposed to receive a meeting link for tomorrow?

**Comment by eyalb181** [comment]
Hey @LadyKerr, no worries. September 6th works great, thanks!

**Comment by eyalb181** [comment]
Done. Looking forward to it!

**Comment by LadyKerr** [comment]
linky again: https://streamyard.com/y2f7yui4zk

**Comment by LadyKerr** [comment]
That was such a great chat! Thanks for hanging!
