### ISSUE TITLE
Open Source Friday - CodeCompass - [08-16-2024]

### ISSUE THREAD

**Issue by miguelgfierro** [githubevents/open-source-friday#72]
### Name

Miguel Fierro

### GitHub Handle

@miguelgfierro

### Tell us about yourself

I'm a Data Scientist at Microsoft and a Professor of chatbots and recommendation systems at IE University. My students have created a chatbot and recommendation system for GitHub.

### Project Name

CodeCompass

### Project Repo Link

https://github.com/RecandChat/CodeCompass

### Stream Date

- [ ] Yes
- [X] Not yet

### Twitter URL

@miguelgfierro

### LinkedIn URL

linkedin.com/in/miguelgfierro

### Additional Information

CodeCompass is a Chabot and Reccomendation engine that aims to enhance the GitHub experience for developers and learners alike by providing a personalized interface to discover and interact with repositories. Our goal is to make learning and discovery in GitHub intuitive, informative, and tailored to each user's interests and needs.

**Comment by miguelgfierro** [comment]
The students who developed the project are: 
- Gabriel de Olaguibel @gabrieldeolaguibel
- Luca Cuneo @Lukasaurus11
- Maud Hovland @maudhelen
- Keti Sulamanidze @KTsula
- Felix Gomez-Guillamon @felixggj
- Miranda Drummond @mirandadrummond

They have a quick YouTube video explaining the project: https://www.youtube.com/watch?v=iaSOjpxsE7s

Feel free to add any comments you consider.

**Comment by AndreaGriffiths11** [comment]
Hi @miguelgfierro apologies for the delay, would August 19th 2024 work for you? If so, please email me at andreagriffiths11@github.com and we can get you scheduled! Thanks again for your patience.

**Comment by miguelgfierro** [comment]
@AndreaGriffiths11 that date works! I'll start an email thread.

**Comment by AndreaGriffiths11** [comment]
Hello everyone,

Thank you very much for your patience. I've been out with a family emergency. I realized I had the wrong date in the schedule. The stream will be live at 1PM ET on August 16th. Once again, would all the students be presenting? The usual flow for the event is to have an introduction to the projects, followed by a demo and Q&A. Could you please reply to this email with a list of responsibilities for the stream? We will stream using Streamyard. Since this is a larger group, I'd like to do a test run - 15 minutes tech check, August 9 prior at the same time. Please notify me if this is not convenient for you all.

| Name                     | Responsibility |
|--------------------------|----------------|
| Gabriel de Olaguibel     |                |
| Luca Cuneo               |                |
| Maud Hovland             |                |
| Keti Sulamanidze         |                |
| Felix Gomez-Guillamon    |                |
| Miranda Drummond         |                |

Please let me know if you have any questions or concerns.

**Comment by gabrieldeolaguibel** [comment]
> Hello everyone,
> 
> Thank you very much for your patience. I've been out with a family emergency. I realized I had the wrong date in the schedule. The stream will be live at 1PM ET on August 16th. Once again, would all the students be presenting? The usual flow for the event is to have an introduction to the projects, followed by a demo and Q&A. Could you please reply to this email with a list of responsibilities for the stream? We will stream using Streamyard. Since this is a larger group, I'd like to do a test run - 15 minutes tech check, August 9 prior at the same time. Please notify me if this is not convenient for you all.
> 
> Name	Responsibility
> Gabriel de Olaguibel	
> Luca Cuneo	
> Maud Hovland	
> Keti Sulamanidze	
> Felix Gomez-Guillamon	
> Miranda Drummond	
> Please let me know if you have any questions or concerns.

Hi Andrea,

We are very excited to be presenting our work on Aug 16th!

Regarding the responsibilities, here is what we decided on:
| Name                     | Responsibility |
|--------------------------|----------------|
| Gabriel de Olaguibel       |  Half of Chatbot Demo          |
| Luca Cuneo                    |   Recommendation System Architecture/ design explanation          |
| Maud Hovland                |   Half of Recommendation system Demo            |
| Keti Sulamanidze           |   Half of Recommendation system Demo              |
| Felix Gomez-Guillamon |    Half of Chatbot Demo           |
| Miranda Drummond       |    Chatbot System Architecture/ design explanation            |
| Miguel Fierro       |    Short intro           |

Regarding the tech check, what other dates could we possibly schedule this for? Most of us have summer internships ending on the 9th and it might be a hectic day for us to fit that in. Also, we plan to only have one person controlling the screen sharing in the stream for simplicity.

Looking forward to it!

Thanks,
Gabriel de Olaguibel

**Comment by AndreaGriffiths11** [comment]
@gabrieldeolaguibel how about next Friday for a tech check? Will that work for the team?

**Comment by gabrieldeolaguibel** [comment]
> @gabrieldeolaguibel how about next Friday for a tech check? Will that work for the team?

@AndreaGriffiths11 this coming Friday (9th) could work for a few members of our team. Some of us are traveling or ending internships that day.

Do you have another day available before our stream on the 16th? If not, we can definitely still connect on the 9th but not all members will be available. Those who are there can cover.

Let me know.

**Comment by AndreaGriffiths11** [comment]
@gabrieldeolaguibel How about the 13 in the evening ET?

**Comment by gabrieldeolaguibel** [comment]
> @gabrieldeolaguibel How about the 13 in the evening ET?

@AndreaGriffiths11 That'll work perfectly! the team confirmed.

**Comment by AndreaGriffiths11** [comment]
- Meetup: [CodeCompass: Open Source AI for Personalized GitHub Discovery](https://www.meetup.com/github/events/302793749/?slug=github&eventId=302693389)

**Comment by miguelgfierro** [comment]
@AndreaGriffiths11 is the session open for any audience or only internal GitHub/Microsoft?

**Comment by AndreaGriffiths11** [comment]
Hi @miguelgfierro the stream is open and live in GitHub's official YouTube channel

**Comment by miguelgfierro** [comment]
Promoted the event on my social:
- X: https://x.com/miguelgfierro/status/1823969166920958200
- Facebook: https://www.facebook.com/share/NPN1dDc8h5sDcb6u/
- LinkedIn: https://www.linkedin.com/posts/miguelgfierro_opensourcefriday-activity-7229735623346016257-clm-/

Feel free to share

**Comment by AndreaGriffiths11** [comment]
Team!!! Amazing job friends ✨
