### ISSUE TITLE
Open Source Friday - GitHub All In Open Source - 05-24-2024

### ISSUE THREAD

**Issue by soyetubo** [githubevents/open-source-friday#76]
### Name

Sarah

### GitHub Handle

Oyetubo

### Tell us about yourself

Participants:

The All In program is a community dedicated to advancing diversity, equity, and inclusion within open source. Under the Access Pillar, we seek to lower barriers to access and provide a clear pathway to success for future developers from underrepresented backgrounds and regions. Our programs offer an on-ramp and support to contributors to open source in various stages of their journey and from all walks of life.  This year, we added an opportunity for peer leaders to join us in supporting the community. The Program Ambassadors are peer leaders in the open-source community. They support All In by promoting and advocating for the program in their communities while helping those enrolled on their learning journey. 

### Project Name

 https://github.com/AllInOpenSource/All-In/blob/main/README.md

### Project Repo Link

https://github.com/AllInOpenSource/All-In/blob/main/README.md

### Stream Date

- [x] Yes
- [ ] Not yet

### Dates

05/24/2024

### Twitter URL

https://twitter.com/allinopensource

### LinkedIn URL

https://www.linkedin.com/company/all-in-open-source/

### Additional Information

Panel discussion featuring All In for Students Peer Ambassadors and All In Africa Regional Ambassadors.

**Comment by AndreaGriffiths11** [comment]
Completed: https://www.youtube.com/watch?v=rqvevlJjGis
