### ISSUE TITLE
Open Source Friday - Kargo - 08-30-2024

### ISSUE THREAD

**Issue by christianh814** [githubevents/open-source-friday#81]
### Name

Christian Hernandez

### GitHub Handle

@christianh814

### Tell us about yourself

I am a well rounded technologist with experience in infrastructure engineering, systems administration, enterprise architecture, tech support, advocacy, and product management. Passionate about OpenSource and containerizing the world one application at a time. I am currently a maintainer of the OpenGitOps project, a maintainer of the Argo Project, contributor to the Kargo project and I currently work as Head of Community at Akuity where I focus on GitOps practices, DevOps, Kubernetes, and Containers.

### Project Name

Kargo

### Project Repo Link

https://github.com/akuity/kargo

### Stream Date

- [ ] Yes
- [X] Not yet

### Twitter URL

@christianh814

### LinkedIn URL

https://www.linkedin.com/in/chernandez1982/

### Additional Information

Kargo is a next-generation continuous delivery and application lifecycle orchestration platform for Kubernetes. It builds upon [GitOps](https://opengitops.dev/) principles and integrates with existing technologies, like [Argo CD](https://argoproj.github.io/cd/), to streamline and automate the progressive rollout of changes across the many stages of an application's lifecycle.

Kargo aims to mitigate the challenges that come with doing environment promotions using GitOps by taking a declarative approach to doing those promotions.

**Comment by AndreaGriffiths11** [comment]
Thanks for your interest @christianh814 are you available August 30?

**Comment by christianh814** [comment]
Hi @AndreaGriffiths11 Yes August 30th works for me!

**Comment by AndreaGriffiths11** [comment]
Great! Could you please email me your preferred picture and short bio to andreagriffiths11@github.com

**Comment by AndreaGriffiths11** [comment]
Thanks @christianh814 I've sent you an invite, it auto declined, please check your email
