### ISSUE TITLE
TresJS

### ISSUE THREAD

**Issue by alvarosabu** [githubevents/open-source-friday#83]
### Name

Alvaro Sabu

### GitHub Handle

@alvarosabu

### Tell us about yourself

Hi 👋, I’m Alvaro, **Creative Software Engineer** from 🇻🇪  living in Barcelona, Spain.

Developer Experience Engineer at [Storyblok](https://www.storyblok.com/)

Author of [TresJS](https://tresjs.org/)

I produce creative content and contribute to open source mainly related to Front-end (Vue, Nuxt, Astro) & 3D (Blender, ThreeJS)

Former founder of Porsche Digital Bcn.

### Project Name

TresJS

### Project Repo Link

https://github.com/Tresjs/tres

### Stream Date

- [ ] Yes
- [X] Not yet

### Twitter URL

@alvarosabu

**Comment by AndreaGriffiths11** [comment]
Please email andreagriffiths11@github.com to schedule
