### ISSUE TITLE
Open Source Friday - Dapr - 08-09-2024

### ISSUE THREAD

**Issue by marcduiker** [githubevents/open-source-friday#86]
### Name

Marc Duiker

### GitHub Handle

@marcduiker

### Tell us about yourself

I'm one of the community managers for the Dapr OSS project. I work for Diagrid (founded by the co-creators of Dapr) as a Sr. Developer Advocate. I really love improving the developer experience, and often use my creative hobbies (drawing pixelart, creative coding) in my work. I've been part of developer communities for a long time (mostly in the .NET & Azure space).

### Project Name

Dapr

### Project Repo Link

https://github.com/dapr/dapr

### Stream Date

- [ ] Yes
- [X] Not yet

### Twitter URL

@marcduiker

### LinkedIn URL

https://linkedin.com/in/mduiker

### Additional Information

Dapr will be 5 years old in October this year. It's part of CNCF (Proposal for CNCF Graduation has been submitted) and the project is used by both large enterprises and small start-ups. There is a [Dapr Discord](https://bit.ly/dapr-discord) the community uses, and every other week there is a community call live stream on [YouTube](https://www.youtube.com/@DaprDev).

**Comment by AndreaGriffiths11** [comment]
Thanks for reaching out @marcduiker, would August 9, 6PM UTC work for you?

**Comment by marcduiker** [comment]
> Thanks for reaching out @marcduiker, would August 9, 6PM UTC work for you?

Hi @AndreaGriffiths11, yes that sounds good!

**Comment by AndreaGriffiths11** [comment]
Tahnk you @marcduiker, mind emailing me a short bio and preferred speaker image to andreagriffiths11@github.com

**Comment by LadyKerr** [comment]
Hey @marcduiker I'll be on stream with you tomorrow as Andrea is traveling!

Im looking forward to chatting and seeing your Dapr demoo!!

**Comment by marcduiker** [comment]
> Hey @marcduiker I'll be on stream with you tomorrow as Andrea is traveling!
> 
> Im looking forward to chatting and seeing your Dapr demoo!!

Looking forward to it @LadyKerr!

**Comment by LadyKerr** [comment]
Stream link: https://streamyard.com/8k84485393
