### ISSUE TITLE
Open Source Friday - Beginner talk about contributing (i.e. Django) - [MM-DD-YYYY]

### ISSUE THREAD

**Issue by mgaligniana** [githubevents/open-source-friday#87]
### Name

Marcelo Galigniana

### GitHub Handle

@mgaligniana

### Tell us about yourself

I'm a python developer, django contributor and member who likes to contribute in every repository I can.

### Project Name

Django

### Stream Date

- [ ] Yes
- [X] Not yet

### Twitter URL

@mgaligniana

### LinkedIn URL

https://www.linkedin.com/in/mgaligniana/

### Additional Information

I would like to talk about my beginner experience contributing to open source.

**Comment by AndreaGriffiths11** [comment]
Hiya Marcelo,
Thank you for your interest in OSF. We appreciate your enthusiasm for contributing. Our project streams are primarily focused on the technical aspects, contributions and development of the projects themselves, rather than individual contributor journeys.

**Comment by mgaligniana** [comment]
Perfect @AndreaGriffiths11, no problem!

Thank you for the streamings! They are really motivated!
