### ISSUE TITLE
Open Source Friday - Social Income - TBD

### ISSUE THREAD

**Issue by novas1r1** [githubevents/open-source-friday#92]
### Name

Verena Zaiser

### GitHub Handle

@novas1r1

### Tell us about yourself

I'm a freelance cross-platform developer from Germany since 2019 and specialized on building mobile apps for iOS and Android using Flutter and Dart. I got into IT at 1999 at the age of 11 because I built my own "virtual riding stable". Since then I always kept learning, studied computer science and media and finished with a masters degree. I was employed as a game and mobile developer for several years before I switched to freelancing. Since I found my passion for Flutter I'm an active member of the Flutter community by managing the Flutter DACH community, having a podcast, being active on X and live streaming coding on twitch. Also I wrote a book about Flutter called "Flutter für Dummies" which is the equivalent of "Flutter for Dummies".

Related to Social Income - I came into the project 2022 and together with my colleague I'm developing the mobile app for the recipients.

### Project Name

Social Income

### Project Repo Link

https://github.com/socialincome-san/public

### Stream Date

- [X] Yes
- [ ] Not yet

### Dates

06-14-2024

### Twitter URL

@verry_codes

### LinkedIn URL

https://www.linkedin.com/in/verena-zaiser/

### Additional Information

I'm also regularly streaming on flutter development (sometimes also social income) twitch under my name "novas1r1".

**Comment by AndreaGriffiths11** [comment]
Hiya @novas1r1 Thank you so much for opening the issue, let's put this on the schedule for a live stream, how is 08-16-2024 10AM PT?

**Comment by AndreaGriffiths11** [comment]
Let me check with my colleague to see about next week if that works, @LadyKerr do you have the slot for June 21st filled? https://github.com/githubevents/open-source-friday/issues/78

**Comment by novas1r1** [comment]
I'm on conferences until 7th of July and need to work a lot the week after, so can't do before 15th of July, sorry :(Am 14.06.2024 17:15 schrieb Andrea Liliana Griffiths ***@***.***>:
Let me check with my colleague to see about next week if that works, @LadyKerr do you have the slot for June 21st filled? #78

**Comment by AndreaGriffiths11** [comment]
hi @novas1r1 revisiting to schedule, are you available September 6th?

**Comment by AndreaGriffiths11** [comment]
Please email andreagriffiths11@github.com to schedule
