### ISSUE TITLE
Open Source Friday - Open Source Apache Iceberg

### ISSUE THREAD

**Issue by AlexMercedCoder** [githubevents/open-source-friday#95]
### Name

Alex Merced

### GitHub Handle

@alexmercedcoder

### Tell us about yourself

Alex Merced is a Senior Technical Evangelist for Dremio and co-author of O'Reilly's "Apache Iceberg: The Definitive Guide". Alex writes and speaks on open source technologies around the data lakehouse like Apache Parquet, Apache Iceberg, Nessie, Polaris and much more. Alex is also the host of several data podcasts like "Datanation", "Catalogs, Metadata and Manifests! Oh My!" and more.

### Project Name

Open Source Apache Iceberg Catalog Projects like Nessie & Polaris

### Project Repo Link

https://github.com/projectnessie/nessie, https://github.com/polaris-catalog/polaris?_fsi=CUIleMV3

### Stream Date

- [ ] Yes
- [X] Not yet

### Twitter URL

@amdatalakehouse

### LinkedIn URL

linkedin.com/in/alexmerced

**Comment by AndreaGriffiths11** [comment]
@AlexMercedCoder will Sept 6th work?

**Comment by AndreaGriffiths11** [comment]
Please email andreagriffiths11@github.com to schedule
